@startuml

start
partition "BasicACL Check" {
:SelectNibbleMask;
if (isContainer?) then (yes)
  :AllowContainerNodeOps;
  stop
else (no)
  if (isOwner?) then (yes)
    :CheckOwner;
  else (isOthers)
    :CheckOthers;
  endif
  if (isSticky?) then (yes)
    :CheckObjectRequestOwnerMatch;
  endif
endif
}

partition "Bearer Check" {
if (hasBearerEnabled?) then (yes)
  if (hasBearer?) then (yes)
    :CheckBearer;
    stop
  else (no)
  endif
endif

}

partition "ExtendedACL Check" {
:CheckExtendedACL;
stop
}

@enduml
