@startuml
participant "Storage\nnodes" as sn
participant "Netmap\ncontract" as netmap
participant "Container\ncontract" as cnr
participant "Inner Ring\nNodes" as ir
participant "Balance\ncontract" as bln

group every 1\3 of epoch (including epoch start)
sn -> cnr: Reporting actual storage state
cnr -> cnr: Normalizes values
...
end

group 1\2 of epoch
ir -> bln: Pay for <cid> container tx
bln <-> netmap: Request basic income rate
bln <-> cnr: Request billing info for <cid>
bln -> bln: Transfer requested amount to SNs
...
end

ir -> netmap: New epoch
@enduml