@startuml
participant "Storage\nnodes" as sn
participant "Netmap contract" as netmap
participant "Container contract" as cnr
participant "Inner Ring\nNodes" as ir
participant "Balance contract" as bln

netmap --> ir: New epoch notification

group 1\3 of epoch
ir -> cnr: StartEstimation
cnr --> sn: StartEstimation
...
ir -> cnr: StopEstimation
cnr --> sn: StopEstimation
...
end

group 2\3 of epoch
ir -> cnr: GetEstimations
ir -> bln: Transfer to bank account
...
end

group 3\3 of epoch
ir -> bln: Get balance of bank account
ir -> bln: Transfer to storage node accounts
...
end

ir -> netmap: NewEpoch

@enduml