@startuml
participant "Storage Node 2" as sn2
participant "Storage Node 1" as sn1
participant "Container contract" as cnr

cnr --> sn1: StartEstimation
sn1 -> sn1: Announce


cnr --> sn2: StartEstimation
sn2 -> sn1: Announce

...later...

cnr --> sn2: StopEstimation
note left
  Ignore, because this node is not
  rendezvous node for container in this
  example
end note

cnr --> sn1: StopEstimation
sn1 -> cnr: Announce
@enduml